#pragma checksum "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "d24c4854b16dacf147caafa20a2b16cafa9a5d8e"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index_old), @"mvc.1.0.view", @"/Views/Home/Index_old.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"d24c4854b16dacf147caafa20a2b16cafa9a5d8e", @"/Views/Home/Index_old.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2bf9f63f8bd1aca83f6c42c7d12b044f67727a38", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index_old : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<Product>>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
  
    ViewBag.Title = "Index";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<div class=\"table\">\r\n\r\n    <table id=\"myTable\">\r\n        <thead>\r\n            <tr>\r\n                <th>\r\n                    ");
#nullable restore
#line 13 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.ID));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 16 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.facilityCode));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 19 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.thingTypeCode));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 22 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.Timestamp));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 25 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.tagID));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 28 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.itemcode));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 31 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.supplier));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 34 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.productDescrip));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 37 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.sGroup));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 40 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.Department));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 43 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.StockType));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 46 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.DocumentNum));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 49 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.brand));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 52 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.serialNUM));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 55 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.status));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");
#nullable restore
#line 58 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index_old.cshtml"
               Write(Html.DisplayNameFor(model => model.exitgatename));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                </th>\r\n            </tr>\r\n        </thead>\r\n    </table>\r\n\r\n\r\n</div>\r\n");
            DefineSection("Scripts", async() => {
                WriteLiteral(@"

    
    <script type=""text/javascript"">
        $(document).ready(function () {
            bindDatatable();
        });

        function bindDatatable() {
            datatable = $('#myTable')
                .DataTable({
                    ""sAjaxSource"": ""/Home/GetData"",
                    ""bServerSide"": true,
                    ""bProcessing"": true,
                    ""bSearchable"": true,
                    ""dom"": 'Bfrtip',
                    ""buttons"": [
                        'csv', 'excel'
                    ],
                    ""order"": [[3, 'desc']],
                    ""language"": {
                        ""emptyTable"": ""No record found."",
                        ""processing"":
                            '<i class=""fa fa-spinner fa-spin fa-3x fa-fw"" style=""color:#2a2b2b;""></i><span class=""sr-only"">Loading...</span> '
                    },
                    ""columns"": [
                        {
                            ""data"": ""id"",
                     ");
                WriteLiteral(@"       ""autoWidth"": true,
                            ""searchable"": true
                        },
                        {
                            ""data"": ""facilityCode"",
                            ""autoWidth"": true,
                            ""searchable"": true
                        },
                        {
                            ""data"": ""thingTypeCode"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },
                        {
                            ""data"": ""timestamp"",
                            ""autoWidth"": true,
                            ""render"": function (mydata) {
                                var date = new Date(parseInt(mydata.substr(6)));
                                var month = date.getMonth() + 1;
				return date.getDate() + ""/"" + month + ""/"" + date.getFullYear() + "" "" + date.getHours() + "":"" + date.getMinutes() + "":"" + date.ge");
                WriteLiteral(@"tSeconds();

                            },
                            ""searchable"": true
                        }, {
                            ""data"": ""tagID"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        }, {
                            ""data"": ""itemcode"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
                            ""data"": ""supplier"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
                            ""data"": ""productDescrip"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
       ");
                WriteLiteral(@"                     ""data"": ""sGroup"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
                            ""data"": ""department"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
                            ""data"": ""stockType"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
                            ""data"": ""documentNum"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },{
                            ""data"": ""brand"",
                            ""autoWidth"": true,
                            ""searchable"": tru");
                WriteLiteral(@"e,
                            ""sortable"": false
                        },{
                            ""data"": ""serialNUM"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false
                        },
                        {
                            ""data"": ""status"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false,
                        },
                        {
                            ""data"": ""exitgatename"",
                            ""autoWidth"": true,
                            ""searchable"": true,
                            ""sortable"": false,
                        }
                    ],
                    ""rowCallback"": function (row, data, index) {
                        if (data.status != ""Sold"") {
                            $('td', row).css('color', 'red');
                ");
                WriteLiteral(@"        }
                    },
                    //For single column
                    //columnDefs: [{
                    //    targets: 14,
                    //    render: function (data, type, row) {
                    //        var s = data;
                    //        if (data.toUpperCase() == ""SOLD"") {
                    //            alert(JSON.stringify(row))
                    //           // $(this).closest('tr').addClass('red');
                    //            s = '<span style=""color:red"">' + data + '</span>';
                    //        }
                    //        return s;
                    //    }
                    //}],
                });
        }
        
    </script>

");
            }
            );
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<Product>> Html { get; private set; }
    }
}
#pragma warning restore 1591
