#pragma checksum "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9d587a5fa32e97c9c153cfa98c91fa09f88b005b"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
using Microsoft.AspNetCore.Http;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"9d587a5fa32e97c9c153cfa98c91fa09f88b005b", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2bf9f63f8bd1aca83f6c42c7d12b044f67727a38", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PagedResult<Product>>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/css/style.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/bootstrap.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/images/Group 23.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString(""), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString(""), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/images/Icon ionic-md-settings.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "InvalidRFIDs", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_8 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_9 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Home", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_10 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "LogOut", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_11 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/images/Group 24.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_12 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "1", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_13 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "2", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_14 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "3", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_15 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/lib/jquery/dist/jquery.min.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_16 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/popper.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_17 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/bootstrap.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 4 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
  
    Layout = null;
    var _val = ViewBag.SwitchValue;
    string loggedUser = @HttpContextAccessor.HttpContext.Session.GetString("UserName");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<style>
    .dropbtn {
        cursor: pointer;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

            .dropdown-content a:hover {
                background-color: #ddd;
            }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }
</style>
");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b11223", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b12339", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n<nav class=\"navbar navbar-expand-lg\">\r\n    <div class=\"container-fluid\">\r\n        <a class=\"navbar-brand\" href=\"#\">\r\n            ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b13601", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
        </a>
        <button class=""navbar-toggler"" type=""button"" data-bs-toggle=""collapse"" data-bs-target=""#navbarSupportedContent"" aria-controls=""navbarSupportedContent"" aria-expanded=""false"" aria-label=""Toggle navigation"">
            <span class=""navbar-toggler-icon""></span>
        </button>
        <div class=""collapse navbar-collapse base-font"" id=""navbarSupportedContent"">
            <ul class=""navbar-nav mx-auto mb-2 mb-lg-0"">
                <li class=""nav-item top-center-text"">
                    <a class=""nav-link text-white"" aria-current=""page"" href=""#"">
                        <span class=""fw-bold"">Exit Gate</span> Report
                    </a>
                </li>
            </ul>
            <div class=""d-flex mt-2"">
                <ul class=""navbar-nav me-auto mb-2 mb-lg-0"">
                    <li class=""nav-item pe-2 top-right-text"">
                        <a class=""nav-link text-white"" href=""#"">
                            <span class=""fw-bold"">User:</span> ");
#nullable restore
#line 71 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                                          Write(loggedUser);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                        </a>
                    </li>
                    <li class=""nav-item py-1 px-2"">
                        <div class=""dropdown"">
                            <a class=""dropbtn pe-1 text-white"">
                                ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b16352", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_6);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                            </a>\r\n                            <div class=\"dropdown-content\">\r\n");
#nullable restore
#line 80 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                 if (loggedUser == "admin")
                                {
                                    

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b18056", async() => {
                WriteLiteral("Invalid RFID");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_7.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_7);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_8.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
#nullable restore
#line 84 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b19727", async() => {
                WriteLiteral("LogOut");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_9.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_9);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_10.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_10);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n                    </li>\r\n                </ul>\r\n                <a href=\"#\">\r\n                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b21271", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_11);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
                </a>
            </div>
        </div>
    </div>
</nav>

<div class=""container-fluid"">
    <div class=""row"">
        <div class=""col"">
            <div class=""text-white fs-28 my-3"">
                <span class=""fw-bold"">Facility:</span> ");
#nullable restore
#line 102 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                                  Write(Model.StoreName.ToString());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"col-md-3\">\r\n            ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b23121", async() => {
                WriteLiteral("\r\n                <input class=\"form-control search-form\" type=\"text\" id=\"myInput\" placeholder=\"Search\">\r\n            ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
        </div>
        <div class=""col-md-9 py-3 py-md-0"">
            <span class=""text-white fs-28 pe-2"">NOT Sold</span>
            <label class=""switch"">
                <input type=""checkbox"" id=""togBtn"">
                <span class=""toggle round""></span>
            </label>
            <span class=""text-white fs-28 ps-4 pe-2"">Auto Refresh</span>

            <span class=""dropdown py-1 pe-3"">
                <select class=""dp-toggle px-2"" aria-label=""Default select example"" id=""selectList"">
                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b25033", async() => {
                WriteLiteral("10");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            BeginWriteTagHelperAttribute();
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __tagHelperExecutionContext.AddHtmlAttribute("selected", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.Minimized);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b26319", async() => {
                WriteLiteral("20");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_12.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_12);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b27497", async() => {
                WriteLiteral("30");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_13.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_13);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b28675", async() => {
                WriteLiteral("40");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_14.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_14);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
                </select>
            </span>

            <label class=""switch"">
                <input type=""checkbox"" id=""dropdownMenuTog"">
                <span class=""toggle round""></span>
            </label>

        </div>
        <div>
");
#nullable restore
#line 137 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
             using (Html.BeginForm("ExportCSV", "Home", FormMethod.Post))
            {

#line default
#line hidden
#nullable disable
            WriteLiteral("                <button type=\"submit\" class=\"btn btn-success\">\r\n                    <i class=\"glyphicon glyphicon glyphicon-download\"></i> Download CSV\r\n                </button>\r\n");
#nullable restore
#line 142 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
            }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"        </div>
    </div>
    <div class=""row my-2 p-3"">
        <table class=""table table-dark table-bordered custom-table"" id=""datatable"">
            <thead>
                <tr>
                    <th scope=""col""> ID</th>
                    <th scope=""col""> Facility Code</th>
                    <th scope=""col"">Thing code</th>
                    <th scope=""col"">Time</th>
                    <th scope=""col"">Tag ID</th>
                    <th scope=""col"">ItemCode</th>
                    <th scope=""col""> Supplier</th>
                    <th scope=""col"">Product Description</th>
                    <th scope=""col""> Group</th>
                    <th scope=""col""> Department</th>
                    <th scope=""col""> Stock Type</th>
                    <th scope=""col""> Document</th>
                    <th scope=""col""> Brand</th>
                    <th scope=""col"">Serial NUM</th>
                    <th scope=""col"">Status</th>
                    <th scope=""col"">Exit Gate Name</th>
  ");
            WriteLiteral("              </tr>\r\n            </thead>\r\n            <tbody>\r\n");
#nullable restore
#line 171 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                  
                    var i = 1;
                

#line default
#line hidden
#nullable disable
#nullable restore
#line 174 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                 foreach (var product in Model.Results)
                {
                    var rowNo = (Model.CurrentPage - 1) * Model.PageSize + i;
                    i++;


#line default
#line hidden
#nullable disable
            WriteLiteral("                <tr>\r\n                    <td scope=\"row\">");
#nullable restore
#line 180 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                               Write(product.ID);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 181 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.facilityCode));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 182 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.thingTypeCode));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 183 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.Timestamp));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n\r\n");
#nullable restore
#line 185 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                     if (product.status.ToLower() == "sold")
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <td class=\"text-green\">");
#nullable restore
#line 187 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                          Write(Html.DisplayTextFor(model => product.tagID));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n");
#nullable restore
#line 188 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                    }
                    else
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <td class=\"text-red\">");
#nullable restore
#line 191 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                        Write(Html.DisplayTextFor(model => product.tagID));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n");
#nullable restore
#line 192 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <td>");
#nullable restore
#line 193 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.itemcode));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 194 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.supplier));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 195 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.productDescrip));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 196 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.sGroup));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 197 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.Department));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 198 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.StockType));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 199 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.DocumentNum));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 200 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.brand));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    <td>");
#nullable restore
#line 201 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.serialNUM));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n\r\n\r\n");
#nullable restore
#line 204 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                     if (product.status.ToLower() == "sold")
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <td class=\"text-green\">");
#nullable restore
#line 206 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                          Write(Html.DisplayTextFor(model => product.status));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n");
#nullable restore
#line 207 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                    }
                    else
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <td class=\"text-red\">");
#nullable restore
#line 210 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                                        Write(Html.DisplayTextFor(model => product.status));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n");
#nullable restore
#line 211 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <td>");
#nullable restore
#line 212 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
                   Write(Html.DisplayTextFor(model => product.exitgatename));

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                </tr>\r\n");
#nullable restore
#line 214 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"


                }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </tbody>\r\n        </table>\r\n        ");
#nullable restore
#line 220 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
    Write(await Component.InvokeAsync<PagerViewComponent>(Model));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n    </div>\r\n    }\r\n    <footer>\r\n        <p class=\"text-center\">\r\n            Copyright 2020 INNOVENT TECH SOLUTIONS, All rights reserved, Confidential\r\n        </p>\r\n    </footer>\r\n</div>\r\n\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b41802", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_15);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b42843", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_16);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9d587a5fa32e97c9c153cfa98c91fa09f88b005b43884", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_17);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n<script type=\"text/javascript\">\r\n    var switchStatus = false;\r\n    var isRefresh = false;\r\n    var selectedValue;\r\n    $(document).ready(function () {\r\n        if (\'");
#nullable restore
#line 239 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
        Write(Model.switchValue);

#line default
#line hidden
#nullable disable
            WriteLiteral("\' === \'True\') {\r\n            $(\"#togBtn\").prop(\'checked\', true);\r\n            switchStatus = true;\r\n        }\r\n        else {\r\n            $(\"#togBtn\").prop(\'checked\', false);\r\n            switchStatus = false;\r\n        }\r\n\r\n        if (\'");
#nullable restore
#line 248 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
        Write(Model.isRefresh);

#line default
#line hidden
#nullable disable
            WriteLiteral("\' === \'True\') {\r\n            $(\"#dropdownMenuTog\").prop(\'checked\', true);\r\n            isRefresh = true;\r\n        }\r\n        else {\r\n            $(\"#dropdownMenuTog\").prop(\'checked\', false);\r\n            isRefresh = false;\r\n        }\r\n\r\n        if (\'");
#nullable restore
#line 257 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Home\Index.cshtml"
        Write(Model.selectedInterval);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"' != '0') {
            if ($(""#dropdownMenuTog"").is(':checked')) {
                isRefresh = true;
                selectedValue = $('#selectList').find("":selected"").val();
                intervalID = setInterval('refreshPage()', selectedValue * 1000);
            }
        }

        $(""#dropdownMenuTog,#selectList"").on('change', function () {
            if ($(""#dropdownMenuTog"").is(':checked')) {
                isRefresh = true;
                selectedValue = $('#selectList').find("":selected"").val();
                intervalID = setInterval('refreshPage()', selectedValue * 1000);
            }
            else {
                isRefresh = false;
                clearInterval(intervalID);
            }
        });

        $('#myInput').on('keyup', function () {
            var searchTerm = $(this).val().toLowerCase();

            $('#datatable tbody tr').each(function () {
                var lineStr = $(this).text().toLowerCase();
                if (lineStr.indexOf(search");
            WriteLiteral(@"Term) === -1) {
                    $(this).hide();
                } else {
                    $(this).show();
                }
            });
        });
    });

    $(""#togBtn"").on('change', function () {
        switchStatus = $(this).is(':checked');
        window.location.href = ""/Home/Index?page="" + 1 + ""&selectedInterval="" + selectedValue + ""&isNotSold="" + switchStatus + ""&isRefresh="" + isRefresh;
    });

    function refreshPage() {
        window.location.href = ""/Home/Index?page="" + 1 + ""&selectedInterval="" + selectedValue + ""&isNotSold="" + switchStatus + ""&isRefresh="" + isRefresh;
    }

</script>

<script type=""text/javascript"">
    function tableToCSVServer() {
        window.location.href = ""/Home/ExportCSVAsync"";
    }

    function tableToCSV() {

        // Variable to store the final csv data
        var csv_data = [];

        // Get each row data
        var rows = document.getElementsByTagName('tr');
        for (var i = 0; i < rows.length; i++) {

");
            WriteLiteral(@"            // Get each column data
            var cols = rows[i].querySelectorAll('td,th');

            // Stores each csv row data
            var csvrow = [];
            for (var j = 0; j < cols.length; j++) {

                // Get the text data of each cell
                // of a row and push it to csvrow
                csvrow.push(cols[j].innerHTML);
            }

            // Combine each column value with comma
            csv_data.push(csvrow.join("",""));
        }

        // Combine each row data with new line character
        csv_data = csv_data.join('\n');

        // Call this function to download csv file
        downloadCSVFile(csv_data);

    }

    function downloadCSVFile(csv_data) {

        // Create CSV file object and feed
        // our csv_data into it
        CSVFile = new Blob([csv_data], {
            type: ""text/csv""
        });

        // Create to temporary link to initiate
        // download process
        var temp_link = document.c");
            WriteLiteral(@"reateElement('a');

        // Download csv file
        temp_link.download = ""ExitGateReport.csv"";
        var url = window.URL.createObjectURL(CSVFile);
        temp_link.href = url;

        // This link should not be displayed
        temp_link.style.display = ""none"";
        document.body.appendChild(temp_link);

        // Automatically click the link to
        // trigger download
        temp_link.click();
        document.body.removeChild(temp_link);
    }
</script>
");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PagedResult<Product>> Html { get; private set; }
    }
}
#pragma warning restore 1591
