#pragma checksum "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ca056c6dd699e50767115efe807d2271ded5ff0f"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared_Components_Pager_Default), @"mvc.1.0.view", @"/Views/Shared/Components/Pager/Default.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"ca056c6dd699e50767115efe807d2271ded5ff0f", @"/Views/Shared/Components/Pager/Default.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2bf9f63f8bd1aca83f6c42c7d12b044f67727a38", @"/Views/_ViewImports.cshtml")]
    public class Views_Shared_Components_Pager_Default : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PagedResultBase>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/css/style.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/images/left-arrow-back.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString(""), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/assets/images/right-arrow-back.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
  
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }

        urlTemplate += "&" + key + "=" + request.Query[key];
    }

    var startIndex = Math.Max(Model.CurrentPage - 5, 1);
    var finishIndex = Math.Min(Model.CurrentPage + 5, Model.PageCount);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "ca056c6dd699e50767115efe807d2271ded5ff0f5956", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n\r\n<div class=\"row\">\r\n    <div style=\"color: #61C954 !important;\" class=\"col-md-8 col-sm-8 items-info\">\r\n        Items ");
#nullable restore
#line 26 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
         Write(Model.FirstRowOnPage);

#line default
#line hidden
#nullable disable
            WriteLiteral(" to ");
#nullable restore
#line 26 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                                  Write(Model.LastRowOnPage);

#line default
#line hidden
#nullable disable
            WriteLiteral(" of ");
#nullable restore
#line 26 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                                                          Write(Model.RowCount);

#line default
#line hidden
#nullable disable
            WriteLiteral(" total\r\n    </div>\r\n</div>\r\n\r\n<div class=\"row\">\r\n    <nav class=\"pagination-nav\">\r\n        <ul class=\"pagination paginate-class rounded\">\r\n");
#nullable restore
#line 33 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
             if (Model.PageCount > 1)
            {

#line default
#line hidden
#nullable disable
            WriteLiteral("                <li class=\"page-item p-1\">\r\n                    <a class=\"page-link paginate-icon\"");
            BeginWriteAttribute("href", " href=\"", 1201, "\"", 1240, 1);
#nullable restore
#line 36 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
WriteAttributeValue("", 1208, urlTemplate.Replace("{0}", "1"), 1208, 32, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" aria-label=\"Previous\">\r\n                        <span aria-hidden=\"true\">\r\n                            ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "ca056c6dd699e50767115efe807d2271ded5ff0f9404", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                        </span>\r\n                    </a>\r\n                </li>\r\n");
#nullable restore
#line 42 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                 for (var i = startIndex; i <= finishIndex; i++)
                {
                    

#line default
#line hidden
#nullable disable
#nullable restore
#line 44 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                     if (i == Model.CurrentPage)
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <li class=\"page-item p-1\"><span class=\"page-link\" style=\"background-color: #61C954 !important;\"> ");
#nullable restore
#line 46 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                                                                                                                    Write(i);

#line default
#line hidden
#nullable disable
            WriteLiteral("</span></li>\r\n");
#nullable restore
#line 47 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                    }
                    else
                    {


#line default
#line hidden
#nullable disable
            WriteLiteral("                        <li class=\"page-item p-1\"><a class=\"page-link\"");
            BeginWriteAttribute("href", " href=\"", 1922, "\"", 1970, 1);
#nullable restore
#line 51 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
WriteAttributeValue("", 1929, urlTemplate.Replace("{0}", i.ToString()), 1929, 41, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 51 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                                                                                                                   Write(i);

#line default
#line hidden
#nullable disable
            WriteLiteral("</a></li>\r\n");
#nullable restore
#line 52 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                    }

#line default
#line hidden
#nullable disable
#nullable restore
#line 52 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
                     
                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                <li class=\"page-item p-1\">\r\n                    <a class=\"page-link paginate-icon\"");
            BeginWriteAttribute("href", " href=\"", 2125, "\"", 2187, 1);
#nullable restore
#line 55 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
WriteAttributeValue("", 2132, urlTemplate.Replace("{0}", Model.PageCount.ToString()), 2132, 55, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" aria-label=\"Next\">\r\n                        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "ca056c6dd699e50767115efe807d2271ded5ff0f14227", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                    </a>\r\n                </li>\r\n");
#nullable restore
#line 59 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\Shared\Components\Pager\Default.cshtml"
            }

#line default
#line hidden
#nullable disable
            WriteLiteral("        </ul>\r\n    </nav>\r\n</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PagedResultBase> Html { get; private set; }
    }
}
#pragma warning restore 1591
