//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("538d47a4-f2db-4e0c-bf3b-00ba954c105a")]
[assembly: System.Reflection.AssemblyCompanyAttribute("ExitGateReportPanel")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("publish")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("ExitGateReportPanel")]
[assembly: System.Reflection.AssemblyTitleAttribute("ExitGateReportPanel")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

