#pragma checksum "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6c7be3c7d381fb2635233f61b7f33cf126aed8d3"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_InvalidRFIDs_Delete), @"mvc.1.0.view", @"/Views/InvalidRFIDs/Delete.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"6c7be3c7d381fb2635233f61b7f33cf126aed8d3", @"/Views/InvalidRFIDs/Delete.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2bf9f63f8bd1aca83f6c42c7d12b044f67727a38", @"/Views/_ViewImports.cshtml")]
    public class Views_InvalidRFIDs_Delete : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<InvalidRFID>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
  
    ViewBag.Title = "Delete";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<h2 style=\"color:white;\">Delete</h2>\r\n\r\n<h3 style=\"color:white;\">Are you sure you want to delete this?</h3>\r\n<div style=\"color:white;\">\r\n    <h4>InvalidRFID</h4>\r\n    <hr />\r\n    <dl class=\"dl-horizontal\">\r\n        <dt>\r\n            ");
#nullable restore
#line 15 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.RFID));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n            ");
#nullable restore
#line 19 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.DisplayFor(model => model.RFID));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n            ");
#nullable restore
#line 23 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.Reason));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n            ");
#nullable restore
#line 27 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.DisplayFor(model => model.Reason));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n            ");
#nullable restore
#line 31 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.DisplayNameFor(model => model.IsEnable));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n            ");
#nullable restore
#line 35 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.DisplayFor(model => model.IsEnable));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n\r\n    </dl>\r\n\r\n");
#nullable restore
#line 40 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
     using (Html.BeginForm()) {
        

#line default
#line hidden
#nullable disable
#nullable restore
#line 41 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
   Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("        <div class=\"form-actions no-color\">\r\n            <input type=\"submit\" value=\"Delete\" class=\"btn btn-danger\" /> |\r\n            ");
#nullable restore
#line 45 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
       Write(Html.ActionLink("Back to List", "Index"));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </div>\r\n");
#nullable restore
#line 47 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Delete.cshtml"
    }

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<InvalidRFID> Html { get; private set; }
    }
}
#pragma warning restore 1591
