#pragma checksum "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "852b67bb7b82b74cb22e5801acef54c8443909ba"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_InvalidRFIDs_Details), @"mvc.1.0.view", @"/Views/InvalidRFIDs/Details.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\_ViewImports.cshtml"
using ExitGateReportPanel.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"852b67bb7b82b74cb22e5801acef54c8443909ba", @"/Views/InvalidRFIDs/Details.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2bf9f63f8bd1aca83f6c42c7d12b044f67727a38", @"/Views/_ViewImports.cshtml")]
    public class Views_InvalidRFIDs_Details : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<InvalidRFID>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
  
    ViewBag.Title = "Details";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<h2 style=\"color:white;\">Details</h2>\r\n\r\n<div style=\"color:white;\">\r\n    <h4>InvalidRFID</h4>\r\n    <hr />\r\n    <dl class=\"dl-horizontal\">\r\n        <dt>\r\n            ");
#nullable restore
#line 14 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.RFID));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n            ");
#nullable restore
#line 18 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
       Write(Html.DisplayFor(model => model.RFID));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n            ");
#nullable restore
#line 22 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.Reason));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n            ");
#nullable restore
#line 26 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
       Write(Html.DisplayFor(model => model.Reason));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n            ");
#nullable restore
#line 30 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.IsEnable));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n            ");
#nullable restore
#line 34 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
       Write(Html.DisplayFor(model => model.IsEnable));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n\r\n    </dl>\r\n</div>\r\n<p>\r\n    ");
#nullable restore
#line 40 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
Write(Html.ActionLink("Edit", "Edit", new { id = Model.ID }));

#line default
#line hidden
#nullable disable
            WriteLiteral(" |\r\n    ");
#nullable restore
#line 41 "D:\Setup\Setup software\asp.net workspace\DotNet Core Report\DotNet Core Report\ExitGateReportPanel\Views\InvalidRFIDs\Details.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</p>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<InvalidRFID> Html { get; private set; }
    }
}
#pragma warning restore 1591
